<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.mya.scripts.SubmitCBCApplicationAsOrgAccntCode" tests="1" time="141.108" ignored="0" failures="1" timestamp="14 May 2018 09:16:24 GMT" skipped="0" hostname="India-PC" errors="0">
  <testcase name="testCBCApplicationAsOrgAccntCode" time="141.108" classname="com.mya.scripts.SubmitCBCApplicationAsOrgAccntCode">
    <failure type="java.lang.AssertionError" message="Element Locator ://input[@id=&#039;pg:SiteTemplate:frm:billingTitle&#039;]] Not found expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Element Locator ://input[@id='pg:SiteTemplate:frm:billingTitle']] Not found expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.mya.util.DriverHelper.sendKeys(DriverHelper.java:95)
	at com.mya.pagehelper.CBCApplicationHelper.FillinData(CBCApplicationHelper.java:29)
	at com.mya.scripts.SubmitCBCApplicationAsOrgAccntCode.testCBCApplicationAsOrgAccntCode(SubmitCBCApplicationAsOrgAccntCode.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testCBCApplicationAsOrgAccntCode -->
</testsuite> <!-- com.mya.scripts.SubmitCBCApplicationAsOrgAccntCode -->
